# Generated by Django 5.2.1 on 2025-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotopath', models.ImageField(upload_to='asistencias/')),
            ],
        ),
    ]
